const XIVoiceActors = [
    {
        id: "21m00Tcm4TlvDq8ikWAM",
        name: "Rachel"
    }, {
        id: "2EiwWnXFnvU5JabPnv8n",
        name: "Clyde"
    }, {
        id: "AZnzlk1XvdvUeBnXmlld",
        name: "Domi"
    }, {
        id: "CYw3kZ02Hs0563khs1Fj",
        name: "Dave"
    }, {
        id: "D38z5RcWu1voky8WS1ja",
        name: "Fin"
    }, {
        id: "EXAVITQu4vr4xnSDxMaL",
        name: "Bella"
    }, {
        id: "ErXwobaYiN019PkySvjV",
        name: "Antoni"
    }, {
        id: "GBv7mTt0atIp3Br8iCZE",
        name: "Thomas"
    }, {
        id: "IKne3meq5aSn9XLyUdCD",
        name: "Charlie"
    }, {
        id: "LcfcDJNUP1GQjkzn1xUU",
        name: "Emily"
    }, {
        id: "MF3mGyEYCl7XYWbV9V6O",
        name: "Elli"
    }, {
        id: "N2lVS1w4EtoT3dr4eOWO",
        name: "Callum"
    }, {
        id: "ODq5zmih8GrVes37Dizd",
        name: "Patrick"
    }, {
        id: "SOYHLrjzK2X1ezoPC6cr",
        name: "Harry"
    }, {
        id: "TX3LPaxmHKxFdv7VOQHJ",
        name: "Liam"
    }, {
        id: "ThT5KcBeYPX3keUQqHPh",
        name: "Dorothy"
    }, {
        id: "TxGEqnHWrfWFTfGW9XjX",
        name: "Josh"
    }, {
        id: "VR6AewLTigWG4xSOukaG",
        name: "Arnold"
    }, {
        id: "XB0fDUnXU5powFXDhCwa",
        name: "Charlotte"
    }, {
        id: "XrExE9yKIg1WjnnlVkGX",
        name: "Matilda"
    }, {
        id: "Yko7PKHZNXotIFUBG7I9",
        name: "Matthew"
    }, {
        id: "ZQe5CZNOzWyzPSCn5a3c",
        name: "James"
    }, {
        id: "Zlb1dXrM653N07WRdFW3",
        name: "Joseph"
    }, {
        id: "bVMeCyTHy58xNoL34h3p",
        name: "Jeremy"
    }, {
        id: "flq6f7yk4E4fJM5XTYuZ",
        name: "Michael"
    }, {
        id: "g5CIjZEefAph4nQFvHAz",
        name: "Ethan"
    }, {
        id: "jBpfuIE2acCO8z3wKNLl",
        name: "Gigi"
    }, {
        id: "jsCqWAovK2LkecY7zXl4",
        name: "Freya"
    }, {
        id: "oWAxZDx7w5VEj9dCyTzz",
        name: "Grace"
    }, {
        id: "onwK4e9ZLuTAKqWW03F9",
        name: "Daniel"
    }, {
        id: "pMsXgVXv3BLzUgSXRplE",
        name: "Serena"
    }, {
        id: "pNInz6obpgDQGcFmaJgB",
        name: "Adam"
    }, {
        id: "piTKgcLEGmPE4e6mEKli",
        name: "Nicole"
    }, {
        id: "t0jbNlBVZ17f02VDIeMI",
        name: "Jessie"
    }, {
        id: "wViXBPUzp2ZZixB1xQuM",
        name: "Ryan"
    }, {
        id: "yoZ06aMxZJJ28mfd3POQ",
        name: "Sam"
    }, {
        id: "z9fAnlkpzviPz146aGWa",
        name: "Glinda"
    }, {
        id: "zcAOhNBS3c14rBihAFp1",
        name: "Giovanni"
    }, {
        id: "zrHiDhphv9ZnVXBqCLjz",
        name: "Mimi"
    }
]

export default XIVoiceActors;